---
title: "Coding Café"
subtitle: "Steno Diabetes Center Aarhus and Aarhus University"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
execute: 
  message: false
  warning: false
  echo: false
---

Welcome to the Coding Café at the [Steno Diabetes Center
Aarhus](https://www.stenoaarhus.dk/forskning/) (SDCA) and the
[Department of Public Health at Aarhus University](https://ph.au.dk/)
(AU-PH).

The Coding Café is a place for anyone working at SDCA and/or AU-PH to
get assistance with **coding** in R (and maybe other languages like
Python in the future). The only prerequisite so far is that you have had
some type of introduction to R, preferably through a course such as
[this](https://r-cubed-intro.rostools.org/) one offered by the Danish
Diabetes and Endocrinology Academy.

The sessions are open and one can join in and out at anytime during the
allotted time. There will be two instructors with experience working in
R. We also highly encourage the participants to interact with each
other - maybe there is someone in the group that has the solution to
your problem.

During the sessions there will be free cake and coffee/tea - or whatever
is appropriate for the time of the day.

## Upcoming schedule

```{r tbl-schedule}
#| tbl-cap: "Upcoming dates, times, and locations for the Café sessions."
schedule <- read.csv(here::here("data", "schedule.csv"))
knitr::kable(schedule)
```

## Practical information

### How to find us
The location of the coding café alternates between the Department of Public Health at Aarhus University (Building 1260-1261, Bartholins Allé 2, 8000 Aarhus - [Link to Google Maps](https://www.google.com/maps/place/Institut+for+Folkesundhed,+Aarhus+Universitet/@56.1661664,10.2058468,19z/data=!4m7!3m6!1s0x464c3fbf0462c881:0x2a6b052ab10f41e9!4b1!8m2!3d56.1660574!4d10.2058163!16s%2Fg%2F11xj2y1z6?hl=da-DK&entry=ttu)) and Steno Diabetes Center at Aarhus University Hospital (Entrance A, Palle Juul-Jensens Blvd. 5, 8200 Aarhus N - [Link to Google Maps](https://www.google.com/maps/place/AUH+Forum/@56.1903228,10.1674529,16.5z/data=!4m15!1m8!3m7!1s0x464c158b564e2c4b:0x6a314a2e58fad86!2sPalle+Juul-Jensens+Blvd.+99,+8200+Aarhus!3b1!8m2!3d56.1918906!4d10.1719926!16s%2Fg%2F11kzxydzkg!3m5!1s0x464c15169bcedc65:0x534d30253a9b8527!8m2!3d56.1900371!4d10.1684204!16s%2Fg%2F11fn4dcj2d?entry=ttu)).
At the Department of Public Health, we usually have the café sessions in the lunch room, which is on the ground floor. At Steno, the sessions are often held in the Spektrummet room, which is on the 4th floor. If you don't know the way, just come to the kitchen area on the 4th floor and we'll pick you up there.


### Things to do before asking for help
Being a good coder in R does not necessarily mean that one just sits down and writes a lot of code like writing a piece of text. Even experienced R users search online for code. The great thing about R is that there is often multiple solutions to a coding problem. What often separates an experienced user from a new user is that the experienced user know what to search for, where to search and understand the replies.

We suggest that you try to search on either Google or directly in [Stackoverflow](https://stackoverflow.com/). As a next step, it can be useful to use AI-tools like ChatGPT-3 but beware that it can make up functions and that it does not always work. 

There are suggestions to try before asking a question.

### Asking a clear coding question
Some issues are simple such as I cannot download this package. Other times what you want to do is more complex and needs a bit of background for a person outside your project to understand what you want to do. Therefore, you need to prepare and provide the context to the person you are asking for help. This could be in the form of showing the structure of your dataset, which functions you used, and what you have tried so far. 

### Note about sensitive data
Many of us work with very sensitive data - especially those working in Denmark's Statistics (DST). If you are working on DST, or something similar where you are not allowed to show the data to enyone else, you need to prepare your question a bit more. We recommend that you find an example dataset that looks similar to the dataset you work with and make a coding example. 

<!-- ## Blogs -->
